//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSeries.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Packages = new HashSet<Package>();
        }
    
        public int CId { get; set; }
        public string CNmae { get; set; }
        public string CPassword { get; set; }
        public string CPhone { get; set; }
        public string CMail { get; set; }
        public string CAddress { get; set; }
        public Nullable<System.DateTime> CDob { get; set; }
        public Nullable<int> PAId { get; set; }
        public string CStatus { get; set; }
    
        public virtual PackageAdmin PackageAdmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package> Packages { get; set; }
    }
}
