//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSeries.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expans
    {
        public int ExpanseId { get; set; }
        public string ExpanseName { get; set; }
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
