//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSeries.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int PId { get; set; }
        public string PName { get; set; }
        public Nullable<double> PPrice { get; set; }
        public string PDesc { get; set; }
        public Nullable<System.DateTime> PStartDate { get; set; }
        public Nullable<System.DateTime> PEndDate { get; set; }
        public string PCode { get; set; }
        public string PStatus { get; set; }
        public Nullable<int> PAId { get; set; }
        public Nullable<int> CId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PackageAdmin PackageAdmin { get; set; }
    }
}
