//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSeries.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Package
    {
<<<<<<< HEAD
        public int PId { get; set; }

        [Required(ErrorMessage = "Please enter  Nmae")]
        public string PName { get; set; }
        [Required(ErrorMessage = "Please enter  Price")]
        public Nullable<double> PPrice { get; set; }
        [Required(ErrorMessage = "Please enter  Decription")]
        public string PDesc { get; set; }
        public Nullable<System.DateTime> PStartDate { get; set; }
        public Nullable<System.DateTime> PEndDate { get; set; }

        [Required(ErrorMessage = "Please enter  Promo Code")]
        public string PCode { get; set; }
        public string PStatus { get; set; }
        public Nullable<int> PAId { get; set; }
        public Nullable<int> CId { get; set; }
=======
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public System.DateTime Desc { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Code { get; set; }
        public string Status { get; set; }
        public int UserId { get; set; }
        public int PackageAdminId { get; set; }
>>>>>>> master
    
        public virtual PackageAdmin PackageAdmin { get; set; }
        public virtual User User { get; set; }
    }
}
