//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSeries.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int Id { get; set; }
        public Nullable<double> Salary1 { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
