//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSeries.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Expanses = new HashSet<Expans>();
            this.Packages = new HashSet<Package>();
            this.Salarys = new HashSet<Salary>();
            this.Videos = new HashSet<Video>();
        }
    
        public int Id { get; set; }
        //name validation
        [Required(ErrorMessage = "Please enter your name.")]
        [MinLength(3, ErrorMessage = "Username must have at least 3 characters.")]
        [MaxLength(49, ErrorMessage = "UserName should not more than 49 characters.")]
        public string Name { get; set; }
        //email validation
        [Required(ErrorMessage = "Please enter your email address.")]
        [DataType(DataType.EmailAddress)]
        [MaxLength(50)]
        [EmailAddress(ErrorMessage = "Invalid Email Address.")]
        public string Email { get; set; }
        //pass validation
        [Required(ErrorMessage = "Please enter your Password.")]
        [MaxLength(49,ErrorMessage ="Password should not be more than 49 characters.")]
        [MinLength(5,ErrorMessage = "Password should need minimum 5 characters.")]
        [DataType(DataType.Password)]
        [RegularExpression("^((?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])|(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[^a-zA-Z0-9])|(?=.*?[A-Z])(?=.*?[0-9])(?=.*?[^a-zA-Z0-9])|(?=.*?[a-z])(?=.*?[0-9])(?=.*?[^a-zA-Z0-9])).{5,}$", ErrorMessage = "Passwords must be at least 5 characters ,upper case, lower case, number and special character.")]
        public string Password { get; set; }

        //phone validation
        [Required(ErrorMessage = "Please enter your phone number.")]
        [RegularExpression(@"\d{11}", ErrorMessage = "Please enter 11 digit Mobile number.")]
        public string Phone { get; set; }
        [Required(ErrorMessage ="Enter your Date of Birth.")]
        public Nullable<System.DateTime> DOB { get; set; }
        public string Role { get; set; }
        [Required(ErrorMessage ="Permanent address must to be enter.")]
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AccountCreateTime { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expans> Expanses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package> Packages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salary> Salarys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video> Videos { get; set; }
    }
}
